server.port=8081
spring.application.name=workshop

# spring.ai.anthropic.api-key=${ANTHROPIC_KEY}
# spring.ai.anthropic.chat.options.model=claude-sonnet-4-5-20250929
spring.threads.virtual.enabled=true

# spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
# spring.datasource.username=nitashav
# spring.datasource.password=
# spring.datasource.driver-class-name=org.postgresql.Driver

# spring.ai.model.embedding=postgresml
# spring.ai.postgresml.embedding.options.transformer=distilbert-base-uncased
# spring.ai.postgresml.embedding.options.vectorType=PG_ARRAY
# spring.ai.postgresml.embedding.options.metadataMode=EMBED
# spring.ai.postgresml.embedding.options.kwargs.device=cpu





spring.ai.openai.api-key=${OPENAI_KEY}
spring.ai.openai.chat.options.model=gpt-4o

management.endpoints.web.exposure.include=metrics,prometheus,health,info
management.metrics.distribution.percentiles-histogram.all=true
management.metrics.enable.all=true

logging.level.org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor=DEBUG