package dev.envycodes.workshop.chat;

import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.client.ChatClient.Prompt;
import org.springframework.ai.chat.client.ChatClient.PromptResponse;
import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.util.StringUtils;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class ChatController {

    private final ChatClient chatClient;

    public ChatController(ChatClient.Builder builder) {
        this.chatClient = builder.build();
    }

    /**
     * A basic example of how to use the chat client to pass a message and call the LLM
     * @param message the message to send to the LLM; defaults to a dad joke about dogs
     * @return the LLM response content
     */
    @GetMapping("/")
    public String joke(@RequestParam(value = "message", defaultValue = "Tell me a dad joke about Dogs") String message) {
        return chatClient.prompt()
                .user(message)
                .call()
                .content(); // short for getResult().getOutput().getContent();
    }

    /**
     * Returns a joke about the specified weather condition.
     * @param weather the weather condition to include in the joke (e.g., "rain", "sunny")
     * @return a weather‑related joke generated by the LLM
     */
    @GetMapping("/jokes-by-weather")
    public String jokesByWeather(@RequestParam String weather) {
        if (!StringUtils.hasText(weather)) {
            return "The 'weather' request parameter must not be empty.";
        }
        String promptTemplate = "Tell me a joke about {{weather}}";
        return chatClient.prompt()
                .user(u -> u.text(promptTemplate).param("weather", weather))
                .call()
                .content();
    }

     /**
     * Returns a joke about the specified weather condition.
     * @param weather the weather condition to include in the joke (e.g., "rain", "sunny")
     * @return a weather‑related joke generated by the LLM
     */
    @GetMapping("/jokes-by-topic")
    public String jokesByWeather(@RequestParam String topic) {
        if (!StringUtils.hasText(weather)) {
            return "The 'weather' request parameter must not be empty.";
        }
        String promptTemplate = "Tell me a joke about {{topc}}";
        return chatClient.prompt()
                .user(u -> u.text(promptTemplate).param("topic", topic))
                .call()
                .content();
    }

    /**
     * What if you didn't want to get a String back, and you wanted the whole response?
     * @param message the message to send to the LLM; defaults to a dad joke about computers
     * @return the full {@link ChatResponse} object
     */
    @GetMapping("jokes-with-response")
    public ChatResponse jokeWithResponse(@RequestParam(value = "message", defaultValue = "Tell me a dad joke about computers") String message) {
        return chatClient.prompt()
                .user(message)
                .call()
                .chatResponse();
    }

}
